# Generated by Django 3.1.4 on 2020-12-29 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_search', '0021_vote_votestar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='votestar',
            options={'ordering': ['-value']},
        ),
        migrations.AlterField(
            model_name='votestar',
            name='value',
            field=models.SmallIntegerField(verbose_name='Значение'),
        ),
    ]
