# Generated by Django 3.1.4 on 2020-12-30 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_search', '0022_auto_20201229_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='book_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book_search.book', verbose_name='К книге'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='top_book_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book_search.bookintop', verbose_name='К книге (топ)'),
        ),
    ]
